// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRWuR-igEA2pfy1NB2i9IjEp11WHnxYMY',
    appId: '1:442612575848:web:5b5f974eb9df7c99b355dd',
    messagingSenderId: '442612575848',
    projectId: 'notes-91fc3',
    authDomain: 'notes-91fc3.firebaseapp.com',
    storageBucket: 'notes-91fc3.appspot.com',
    measurementId: 'G-25GRRFSHBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB5PrraCDu680tzGE2JZG_x17HD0_Tegw',
    appId: '1:442612575848:android:ca2eab6eaf5f943eb355dd',
    messagingSenderId: '442612575848',
    projectId: 'notes-91fc3',
    storageBucket: 'notes-91fc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFQ0NqAcc4xElvEBe1mLVb6kh2zZO_Tb8',
    appId: '1:442612575848:ios:594fdf65bc2508cbb355dd',
    messagingSenderId: '442612575848',
    projectId: 'notes-91fc3',
    storageBucket: 'notes-91fc3.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFQ0NqAcc4xElvEBe1mLVb6kh2zZO_Tb8',
    appId: '1:442612575848:ios:2bc21c2166ba115eb355dd',
    messagingSenderId: '442612575848',
    projectId: 'notes-91fc3',
    storageBucket: 'notes-91fc3.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
